/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GameGrid: typeof import('./components/GameGrid.vue')['default']
    GameState: typeof import('./components/GameState.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    OpponentGrid: typeof import('./components/OpponentGrid.vue')['default']
    OpponentGrid1: typeof import('./components/OpponentGrid1.vue')['default']
    OpponentGrid2: typeof import('./components/OpponentGrid2.vue')['default']
    OpponentGrid3: typeof import('./components/OpponentGrid4.vue')['default']
    OpponentGrid4: typeof import('./components/OpponentGrid4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
