/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Connection: typeof import('./components/Connection.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GameCell: typeof import('./components/GameCell.vue')['default']
    GameGrid: typeof import('./components/GameGrid.vue')['default']
    GameStateButton: typeof import('./components/GameStateButton.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    OpponentGrid: typeof import('./components/OpponentGrid.vue')['default']
    OpponentGrid1: typeof import('./components/OpponentGrid1.vue')['default']
    OpponentGrid2: typeof import('./components/OpponentGrid2.vue')['default']
    OpponentGrid4: typeof import('./components/OpponentGrid4.vue')['default']
    OpponentView: typeof import('./components/OpponentView.vue')['default']
    PlayerView: typeof import('./components/PlayerView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}
